### ISSUE TITLE
make work on python 3

### ISSUE THREAD

**Issue by esheldon** [jobovy/extreme-deconvolution#12]
I've already got the changes ready.  If you make a new branch (e.g. py3) I can send a pull request against it.

**Comment by esheldon** [comment]
(or I could send it against master if you want)

**Comment by jobovy** [comment]
If you can make the changes in a way such that python2 still works, feel free to submit against master.

**Comment by jobovy** [comment]
I believe python 3 should now work (at least python 3.5). Ran into this problem myself and made most of the changes before remembering that you had opened this issue!

**Comment by esheldon** [comment]
ok, great!  sorry I got busy and had to put this aside
