### ISSUE TITLE
Installation successful, but not able to load

### ISSUE THREAD

**Issue by tingyuansen** [jobovy/extreme-deconvolution#15]
Hi Jo,

Another not easy to install package :-) . I think I figured out most. It seems like I can get through make, make install, make pywrapper without any error:

**Belkin52:extreme-deconvolution-1.4 yting$ make pywrapper**

_(ls /usr/local/lib/libextremedeconvolution.dylib || (echo "Cannot find library '/usr/local/lib/libextremedeconvolution.dylib', run again with 'INSTALL_DIR=' set to the directory you installed the library in" && exit -1))
/usr/local/lib/libextremedeconvolution.dylib
(ls py/.extreme_deconvolution.py || mv py/extreme_deconvolution.py py/.extreme_deconvolution.py)
py/.extreme_deconvolution.py
sed "s#TEMPLATE_LIBRARY_PATH#'/usr/local/lib/'#g" py/extreme_deconvolution_TEMPLATE.py > py/extreme_deconvolution.py
((cd py && echo 'import extreme_deconvolution' | python) && echo 'Successfully installed Python wrapper' || (echo 'Something went wrong installing Python wrapper' && exit -1))
Successfully installed Python wrapper_

But somehow python cannot find the package. I have been digging for quite a while, but could not really understand why. Any idea?

_>>> import extreme_deconvolution
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'extreme_deconvolution'_

Thank you

**Comment by jobovy** [comment]
You have to add the ``py/`` directory to your ``PYTHONPATH``, did you do that?
