### ISSUE TITLE
stdlib.h not found on Mac 10.14

### ISSUE THREAD

**Issue by Zepeng-Mu** [jobovy/extreme-deconvolution#21]
I am trying to install the R package on Mac. I already installed GSL, and running `make rpackage` I got this error:

```
In file included from /usr/local/include/gsl/gsl_matrix.h:4:0,
                 from bovy_det.c:15:
/usr/local/include/gsl/gsl_matrix_complex_long_double.h:23:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
```

How can I solve this problem? Thanks

**Comment by jobovy** [comment]
Have you installed the [Xcode command-line tools](https://developer.apple.com/xcode/features/)? If you haven't, I believe you can do this with 
```
xcode-select --install
```
in a terminal window. The file should be at ``/usr/include/stdlib.h`` I believe, check whether this exists.

If that doesn't solve it, please mention your Mac OS version and compiler details.

**Comment by Zepeng-Mu** [comment]
Hi, so when I try to install Xcode, I got `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. So I actually installed it before although I do not have the IDE installed. Also, the `/usr/include` folder does not exist on my computer. I am using Mojave and I changed the compiler to `CC=gcc-4.9` in both Makefile and R's Makevars.
Thanks

**Comment by jobovy** [comment]
Perhaps this would work: https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja ?

**Comment by Zepeng-Mu** [comment]
Thank you so much! I decided to install it on Linux cluster in the end and did so without any difficulty.

**Comment by jobovy** [comment]
Great that it works. If you could test the fix suggested in the stackoverflow so future users know whether that fixes this issue, I would be very grateful. Otherwise I will just close the issue. Thanks!

**Comment by Zepeng-Mu** [comment]
> Perhaps this would work: https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja ?

Yes, this works for Mojave, I am guessing that updating to the latest version of Mojave might work as well.

**Comment by jobovy** [comment]
Great, thanks for checking!
