### ISSUE TITLE
Relative import compatible with Python3

### ISSUE THREAD

**Issue by eztean** [jobovy/extreme-deconvolution#25]
I installed the package in my Python3/anaconda distribution. The installation was successful following the instructions of "INSTALL_PYTHON". However, in order to call the function extreme_deconvolution() from outside as:
`from extreme_deconvolution import extreme_deconvolution`
I think that the __init__.py file should be changed from 
https://github.com/jobovy/extreme-deconvolution/blob/7731029f8d533f4d86f4a63ea3f1205a39c7f866/py/__init__.py#L1
to:
`from .extreme_deconvolution import extreme_deconvolution`

Thanks!

**Comment by jobovy** [comment]
Thanks for reporting. Yes, this should probably be changed, but could you tell me which python version you are using? Are you able to install the package with the README `make`, `make install`, `make pywrapper` sequence? Just trying to figure out exactly where the issue lies...

**Comment by eztean** [comment]
I'm using Python 3.6.8 (anaconda installation). Yes, it seems I can do the installation with those commands, but the python package is installed in the py/ subdirectory and not in the anaconda distribution.

**Comment by jobovy** [comment]
Thanks for checking! Yes, that's the problem with the alternative installation, you need to add the package to your PYTHONPATH manually then. I'll see whether the __init__.py fix works without messing anything else up...

**Comment by jobovy** [comment]
Fixed now in 423f81a
