### ISSUE TITLE
make pywrapper , "gsl_rng_mt19937"  error

### ISSUE THREAD

**Issue by lqm03101313** [jobovy/extreme-deconvolution#7]
error information, I am using ubuntu 14.04 with gsl in system directory

(ls /usr/local/lib/libextremedeconvolution.so || (/bin/echo -e "Cannot find library '/usr/local/lib/libextremedeconvolution.so', run again with 'INSTALL_DIR=' set to the directory you installed the library in" && exit -1))
/usr/local/lib/libextremedeconvolution.so
(ls py/.extreme_deconvolution.py || mv py/extreme_deconvolution.py py/.extreme_deconvolution.py)
py/.extreme_deconvolution.py
sed "s#TEMPLATE_LIBRARY_PATH#'/usr/local/lib/'#g" py/extreme_deconvolution_TEMPLATE.py > py/extreme_deconvolution.py
((cd py && /bin/echo -e 'import extreme_deconvolution' | python) && /bin/echo -e 'Successfully installed Python wrapper' || (/bin/echo -e 'Something went wrong installing Python wrapper' && exit -1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "extreme_deconvolution.py", line 18, in <module>
    _lib = ctypes.CDLL(p)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libextremedeconvolution.so: undefined symbol: gsl_rng_mt19937
Something went wrong installing Python wrapper
make: *** [pywrapper] 错误 255

**Comment by jobovy** [comment]
Hi,

Please describe your problem in somewhat more detail. It seems like the GSL is not being properly linked, so you might want to check that the C linker can find it.
