### ISSUE TITLE
partially fix covariance 

### ISSUE THREAD

**Issue by jhmarcus** [jobovy/extreme-deconvolution#9]
Is is possible to fix a single covariance matrix and estimate the others? Specially I would like setup a mixture model with one component as a spike fixed at 0 and estimate the covariance matrices in the rest of the components.

**Comment by jobovy** [comment]
The ``fixcovar`` input can be a list where you set one to ``True`` and the rest to ``False``: see [this documentation](https://github.com/jobovy/extreme-deconvolution/blob/master/py/extreme_deconvolution.py#L51).

**Comment by jhmarcus** [comment]
Great thank you!
